server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080
 
logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
    - type: file
      threshold: ALL
      currentLogFilename: ./log/xdropwizard.log
      archivedLogFilenamePattern: ./log/xdropwizard-%d.log.gz,
      archivedFileCount: 5
      timeZone: UTC
      
#http:
#rootPath: /service/*  replaced by environment.jersey().setUrlPattern("/service/*");

displayName: training